/**
 * Reactive UI strings for App.vue (reactive to locale).
 */
import { computed, type Ref } from "vue";
import { locale, t, type LocaleKey } from "../i18n";
import type { IdeKind } from "../types/relay-app";

function detectSubmitModifierLabel(): "⌘" | "Ctrl" {
  if (typeof navigator === "undefined") return "Ctrl";
  const uaData = (navigator as Navigator & { userAgentData?: { platform?: string } })
    .userAgentData;
  const platform = `${uaData?.platform ?? ""} ${navigator.platform ?? ""} ${navigator.userAgent ?? ""}`.toLowerCase();
  return platform.includes("mac") ? "⌘" : "Ctrl";
}

function localizeModifierInText(input: string, modifier: "⌘" | "Ctrl"): string {
  return input
    .split("⌘/Ctrl").join(modifier)
    .split("⌘ or Ctrl").join(modifier);
}

export function useAppStrings(ideLabel: Ref<string>, ideKind: Ref<IdeKind | null>, enterSubmitModOnly?: Ref<boolean>) {
  const strings = computed(() => {
    void locale.value;
    const ide = ideLabel.value || "IDE";
    const ideCliId = ideKind.value || "other";
    const modOnly = enterSubmitModOnly?.value ?? false;
    const submitModifier = detectSubmitModifierLabel();
    const shortcutText = (key: LocaleKey) =>
      localizeModifierInText(t(key), submitModifier);
    return {
      appTitle: t("appTitle"),
      mainHintPreview: modOnly ? shortcutText("mainHintPreviewMod") : shortcutText("mainHintPreview"),
      tabStripAria: t("tabStripAria"),
      tabCloseAria: t("tabCloseAria"),
      tabCloseTitle: t("tabCloseTitle"),
      windowDockAria: t("windowDockAria"),
      windowDockLeft: t("windowDockLeft"),
      windowDockCenter: t("windowDockCenter"),
      windowDockRight: t("windowDockRight"),
      dockBtnLeft: t("dockBtnLeft"),
      dockBtnCenter: t("dockBtnCenter"),
      dockBtnRight: t("dockBtnRight"),
      dockEdgeHideAria: t("dockEdgeHideAria"),
      dockEdgeHideTitle: t("dockEdgeHideTitle"),
      windowAlwaysOnTopAria: t("windowAlwaysOnTopAria"),
      windowAlwaysOnTopTitle: t("windowAlwaysOnTopTitle"),
      qaHistoryTitle: t("qaHistoryTitle"),
      qaAssistantTurn: t("qaAssistantTurn"),
      qaUserTurnMe: t("qaUserTurnMe"),
      qaNoRetellYet: t("qaNoRetellYet"),
      composerAriaRegion: t("composerAriaRegion"),
      composerHint: modOnly ? shortcutText("composerHintMod") : shortcutText("composerHint"),
      composerAttach: t("composerAttach"),
      composerThumbRemove: t("composerThumbRemove"),
      composerFileDropAria: t("composerFileDropAria"),
      composerFileDropRemove: t("composerFileDropRemove"),
      composerImageZoomTitle: t("composerImageZoomTitle"),
      imageLightboxClose: t("imageLightboxClose"),
      composerSubmitIconTitle: modOnly
        ? shortcutText("composerSubmitIconTitleMod")
        : shortcutText("composerSubmitIconTitle"),
      composerSubmitIconAria: t("composerSubmitIconAria"),
      composerSubmitting: t("composerSubmitting"),
      composerSubmitDisabledPreview: modOnly
        ? shortcutText("composerSubmitDisabledPreviewMod")
        : shortcutText("composerSubmitDisabledPreview"),
      composerImageAria: t("composerImageAria"),
      qaSkipped: t("qaSkipped"),
      qaSkippedIdle: t("qaSkippedIdle"),
      qaEmptySubmit: t("qaEmptySubmit"),
      placeholder: t("placeholder"),
      slashListboxAria: t("slashListboxAria"),
      slashNoMatch: t("slashNoMatch"),
      slashNoCommandsForSession: t("slashNoCommandsForSession"),
      slashDropdownHint: t("slashDropdownHint"),
      composerHintDraft: modOnly
        ? shortcutText("composerHintDraftMod")
        : shortcutText("composerHintDraft"),
      composerSubmitDisabledIdle: t("composerSubmitDisabledIdle"),
      composerRelayExitTitle: t("composerRelayExitTitle"),
      composerRelayExitAria: t("composerRelayExitAria"),
      composerSubmitBlockedFileError: t("composerSubmitBlockedFileError"),
      ideBlockingHint: t("ideBlockingHint"),
      noteExpired: t("noteExpired"),
      loading: t("loading"),
      noLaunch: t("noLaunch"),
      pathEnvBtn: t("pathEnvBtn"),
      pathEnvBusy: t("pathEnvBusy"),
      segSetup: t("segSetup"),
      segCache: t("segCache"),
      setupTitle: t("setupTitle"),
      mcpPauseTitle: t("mcpPauseTitle"),
      mcpPauseHint: t("mcpPauseHint"),
      mcpPauseSwitch: t("mcpPauseSwitch"),
      mcpPauseSwitchTitle: t("mcpPauseSwitchTitle"),
      mcpPauseStatusOn: t("mcpPauseStatusOn"),
      mcpPauseStatusOff: t("mcpPauseStatusOff"),
      setupLead: t("setupLead", { ide }),
      setupAllReadyLead: t("setupAllReadyLead", { ide }),
      setupStatus: t("setupStatus"),
      setupChipPath: t("setupChipPath"),
      setupPathExplain: t("setupPathExplain"),
      setupMcpExplain: t("setupMcpExplain", { ide }),
      setupRuleExplain: t("setupRuleExplain", { ide }),
      setupConfigFile: t("setupConfigFile"),
      setupBinDir: t("setupBinDir"),
      setupOn: t("setupOn"),
      setupOff: t("setupOff"),
      setupBtnPublicInstall: t("setupBtnPublicInstall"),
      setupBtnPublicUninstall: t("setupBtnPublicUninstall"),
      setupBtnIdeInstall: t("setupBtnIdeInstall", { ide }),
      setupBtnIdeUninstall: t("setupBtnIdeUninstall", { ide }),
      setupSectionPublic: t("setupSectionPublic"),
      setupSectionIde: t("setupSectionIde"),
      setupToolParamsTitle: t("setupToolParamsTitle"),
      setupToolParamsLead: t("setupToolParamsLead", { ide, ideCliId }),
      mcpCopy: t("mcpCopy"),
      setupAdvanced: t("setupAdvanced"),
      setupAdvPathTitle: t("setupAdvPathTitle"),
      setupAdvPathLead: t("setupAdvPathLead"),
      setupIdeGuide: t("setupIdeGuide"),
      settingsTitle: t("settingsTitle"),
      appAuthorLine: t("appAuthorLine"),
      appAuthorEmailAria: t("appAuthorEmailAria"),
      settingsBack: t("settingsBack"),
      ariaOpenSettings: t("ariaOpenSettings"),
      settingsCheckStatus: t("settingsCheckStatus"),
      settingsLangAria: t("settingsLangAria"),
      settingsChecking: t("settingsChecking"),
      publicUninstallConfirm: t("publicUninstallConfirm"),
      ideUninstallConfirm: t("ideUninstallConfirm", { ide }),
      setupUninstallConfirmBtn: t("setupUninstallConfirmBtn"),
      setupUninstallCancel: t("setupUninstallCancel"),
      segRulePrompts: t("segRulePrompts"),
      rulePromptsTitle: t("rulePromptsTitle"),
      rulePromptsLead: t("rulePromptsLead"),
      rulePromptsSectionIde: t("rulePromptsSectionIde", { ide }),
      rulePromptsModeLoop: t("rulePromptsModeLoop"),
      rulePromptsModeLoopDesc: t("rulePromptsModeLoopDesc"),
      rulePromptsModeTool: t("rulePromptsModeTool"),
      rulePromptsModeToolDesc: t("rulePromptsModeToolDesc"),
      rulePromptsCopy: t("rulePromptsCopy"),
      rulePromptsViewMd: t("rulePromptsViewMd"),
      rulePromptsViewSource: t("rulePromptsViewSource"),
      rulePromptsToggleEnAria: t("rulePromptsToggleEnAria"),
      rulePromptsLabelBilingual: t("rulePromptsLabelBilingual"),
      rulePromptsInstallCursor: t("rulePromptsInstallCursor", { ide }),
      rulePromptsUpdateCursor: t("rulePromptsUpdateCursor", { ide }),
      rulePromptsRemoveCursor: t("rulePromptsRemoveCursor", { ide }),
      rulePromptsInstalledBadge: t("rulePromptsInstalledBadge"),
      appTrayTitle: t("appTrayTitle"),
      appTrayCloseToTray: t("appTrayCloseToTray"),
      appTrayCloseToTrayHint: t("appTrayCloseToTrayHint"),
      appMcpWaitTitle: t("appMcpWaitTitle"),
      appIdleTimeoutLabel: t("appIdleTimeoutLabel"),
      appIdleTimeoutHint: t("appIdleTimeoutHint"),
      appIdleTimeoutSaved: t("appIdleTimeoutSaved"),
      appIdleTimeoutUnit: t("appIdleTimeoutUnit"),
      appEnterSubmitTitle: t("appEnterSubmitTitle"),
      appEnterSubmitLabel: t("appEnterSubmitLabel"),
      appEnterSubmitPlain: t("appEnterSubmitPlain"),
      appEnterSubmitModOnly: shortcutText("appEnterSubmitModOnly"),
      appEnterSubmitSaved: t("appEnterSubmitSaved"),
      appSaveErr: t("appSaveErr"),
      cacheTitle: t("cacheTitle"),
      cacheSubtitle: t("cacheSubtitle"),
      cacheLead: t("cacheLead"),
      cacheSectionStorage: t("cacheSectionStorage"),
      cacheAutoTitle: t("cacheAutoTitle"),
      cacheAutoLead: t("cacheAutoLead"),
      cacheAutoSelectLabel: t("cacheAutoSelectLabel"),
      cacheManualTitle: t("cacheManualTitle"),
      cacheRetentionTriggerAria: t("cacheRetentionTriggerAria"),
      cacheDataDir: t("cacheDataDir"),
      cacheOpenFolder: t("cacheOpenFolder"),
      cacheLoading: t("cacheLoading"),
      cacheLoadErr: t("cacheLoadErr"),
      cacheTotal: t("cacheTotal"),
      cacheAttachments: t("cacheAttachments"),
      cacheLogs: t("cacheLogs"),
      cacheRefresh: t("cacheRefresh"),
      cacheClearAll: t("cacheClearAll"),
      cacheClearAttach: t("cacheClearAttach"),
      cacheClearLogs: t("cacheClearLogs"),
      cacheBusy: t("cacheBusy"),
      cacheConfirmModalTitle: t("cacheConfirmModalTitle"),
      cacheConfirmBtn: t("cacheConfirmBtn"),
      cacheCancelBtn: t("cacheCancelBtn"),

      segUsage: t("segUsage"),
      usageTitle: t("usageTitle"),
      usageLead: t("usageLead"),
      usageCapsuleTitle: t("usageCapsuleTitle"),
      usagePopoverTitle: t("usagePopoverTitle"),
      usageMonthSummary: t("usageMonthSummary"),
      usagePlanUsed: t("usagePlanUsed"),
      usagePlanRemaining: t("usagePlanRemaining"),
      usageOnDemandUsed: t("usageOnDemandUsed"),
      usageTeamOnDemand: t("usageTeamOnDemand"),
      usageMembership: t("usageMembership"),
      usagePlanCost: t("usagePlanCost"),
      usageOnDemandCap: t("usageOnDemandCap"),
      usageOnDemandNoLimit: t("usageOnDemandNoLimit"),
      usageOnDemandViewDashboard: t("usageOnDemandViewDashboard"),
      usageOnDemandDisabled: t("usageOnDemandDisabled"),
      usageBillingCycle: t("usageBillingCycle"),
      usageResetsIn: t("usageResetsIn"),
      usageDays: t("usageDays"),
      usageDailyAvg: t("usageDailyAvg"),
      usageReqPerDay: t("usageReqPerDay"),
      usageExhaustedIn: t("usageExhaustedIn"),
      usageExhaustedDays: t("usageExhaustedDays"),
      usageRecentTitle: t("usageRecentTitle"),
      usageNoEvents: t("usageNoEvents"),
      usageLoadMore: t("usageLoadMore"),
      usageTokUnit: t("usageTokUnit"),
      usageSettingsTokenTitle: t("usageSettingsTokenTitle"),
      usageSettingsAutoHint: t("usageSettingsAutoHint"),
      usageSettingsIdeLoginHint: t("usageSettingsIdeLoginHint"),
      usageSettingsTokenConfigured: t("usageSettingsTokenConfigured"),
      usageSettingsRefreshTitle: t("usageSettingsRefreshTitle"),
      usageSettingsRefreshHint: t("usageSettingsRefreshHint"),
      usageSettingsRefreshInterval: t("usageSettingsRefreshInterval"),
      usageSettingsRefreshIntervalUnit: t("usageSettingsRefreshIntervalUnit"),
      usageRefreshing: t("usageRefreshing"),
      usageRefreshErr: t("usageRefreshErr"),
      usageRefreshBtn: t("usageRefreshBtn"),
      usageLastRefreshed: t("usageLastRefreshed"),
      usageNever: t("usageNever"),

      // IDE selection
      ideSelectionTitle: t("ideSelectionTitle"),
      ideSelectionSubtitle: t("ideSelectionSubtitle"),
      ideCursor: t("ideCursor"),
      ideCursorDesc: t("ideCursorDesc"),
      ideClaudeCode: t("ideClaudeCode"),
      ideClaudeCodeDesc: t("ideClaudeCodeDesc"),
      ideWindsurf: t("ideWindsurf"),
      ideWindsurfDesc: t("ideWindsurfDesc"),
      ideOther: t("ideOther"),
      ideOtherDesc: t("ideOtherDesc"),
      ideSettingsChangeBtn: t("ideSettingsChangeBtn"),
      ideSelectPlaceholder: t("ideSelectPlaceholder"),

      // Remote SSH
      segRemote: t("segRemote"),
      remoteTitle: t("remoteTitle"),
      remoteLead: t("remoteLead"),
      remoteAddBtn: t("remoteAddBtn"),
      remoteEmptyHint: t("remoteEmptyHint"),
      remoteConnectBtn: t("remoteConnectBtn"),
      remoteDisconnectBtn: t("remoteDisconnectBtn"),
      remoteRemoveBtn: t("remoteRemoveBtn"),
      remoteTestBtn: t("remoteTestBtn"),
      remoteTestingBtn: t("remoteTestingBtn"),
      remoteTestOk: t("remoteTestOk"),
      remoteTestFail: t("remoteTestFail"),
      remoteAddTitle: t("remoteAddTitle"),
      remoteSshTarget: t("remoteSshTarget"),
      remoteSshPort: t("remoteSshPort"),
      remoteSshKey: t("remoteSshKey"),
      remoteProxyJump: t("remoteProxyJump"),
      remoteIdeKind: t("remoteIdeKind"),
      remoteRelayPath: t("remoteRelayPath"),
      remoteCancelBtn: t("remoteCancelBtn"),
      remoteSaveBtn: t("remoteSaveBtn"),
      remoteSavingBtn: t("remoteSavingBtn"),
      remoteStatusConnected: t("remoteStatusConnected"),
      remoteStatusConnecting: t("remoteStatusConnecting"),
      remoteStatusDisconnected: t("remoteStatusDisconnected"),
      remoteStatusReconnecting: t("remoteStatusReconnecting"),
      remoteStatusError: t("remoteStatusError"),
      remoteRemoveConfirm: t("remoteRemoveConfirm"),
      remoteRemoveConfirmBtn: t("remoteRemoveConfirmBtn"),
      remoteSaveErr: t("remoteSaveErr"),
      remoteRemoveErr: t("remoteRemoveErr"),
      remotePreemptBtn: t("remotePreemptBtn"),
      remoteReleaseBtn: t("remoteReleaseBtn"),
      remoteRoutingLocal: t("remoteRoutingLocal"),
      remoteRoutingRemote: t("remoteRoutingRemote"),
      remotePreemptHint: t("remotePreemptHint"),
      remoteReclaimBtn: t("remoteReclaimBtn"),
      remoteReclaimOk: t("remoteReclaimOk"),
      remoteLocalPinLabel: t("remoteLocalPinLabel"),
      remoteLocalPinHint: t("remoteLocalPinHint"),
      remoteLocalPinOn: t("remoteLocalPinOn"),
      remoteLocalPinOff: t("remoteLocalPinOff"),
      remotePreemptPinnedErr: t("remotePreemptPinnedErr"),
      remoteLoadingText: t("remoteLoadingText"),
      remoteLoadError: t("remoteLoadError"),
      remoteRetryBtn: t("remoteRetryBtn"),
      remoteDetailPort: t("remoteDetailPort"),
      remoteDetailKey: t("remoteDetailKey"),
      remoteDetailJump: t("remoteDetailJump"),
      remoteDetailLast: t("remoteDetailLast"),

      // Session manager
      sessionTitle: t("sessionTitle"),
      sessionEmpty: t("sessionEmpty"),
      sessionRefresh: t("sessionRefresh"),
      sessionDisconnect: t("sessionDisconnect"),
      sessionDisconnectAll: t("sessionDisconnectAll"),
      sessionDisconnectLocalAll: t("sessionDisconnectLocalAll"),
      sessionDisconnectRemoteAll: t("sessionDisconnectRemoteAll"),
      sessionOriginLocal: t("sessionOriginLocal"),
      sessionOriginRemote: t("sessionOriginRemote"),
      sessionPid: t("sessionPid"),
      sessionHost: t("sessionHost"),
      sessionConnectedAt: t("sessionConnectedAt"),
      sessionTabTitle: t("sessionTabTitle"),
      sessionIde: t("sessionIde"),
      sessionDisconnectOk: t("sessionDisconnectOk"),
      sessionDisconnectAllOk: t("sessionDisconnectAllOk"),
      sessionDisconnectErr: t("sessionDisconnectErr"),
      sessionDisconnectConn: t("sessionDisconnectConn"),
      sessionDisconnectConnOk: t("sessionDisconnectConnOk"),
      sessionConnLabel: t("sessionConnLabel"),
      sessionPreemptLocal: t("sessionPreemptLocal"),
      sessionPreemptRemote: t("sessionPreemptRemote"),
      sessionPreemptOk: t("sessionPreemptOk"),
      sessionPreemptErr: t("sessionPreemptErr"),
      sessionRemoteHint: t("sessionRemoteHint"),
      sessionRemotePreemptHere: t("sessionRemotePreemptHere"),
      sessionRemotePreemptHereOk: t("sessionRemotePreemptHereOk"),
      sessionRemotePreemptHereErr: t("sessionRemotePreemptHereErr"),
    };
  });
  return { strings };
}
